# Generated by Django 5.1 on 2024-08-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('POI', 'Point of Interest'), ('City', 'City'), ('Region', 'Region')], max_length=20)),
                ('landscape', models.CharField(choices=[('Beach', 'Beach'), ('Mountains', 'Mountains'), ('Forest', 'Forest'), ('Desert', 'Desert'), ('Urban', 'Urban/Cities'), ('Countryside', 'Countryside'), ('Lakes/Rivers', 'Lakes/Rivers')], max_length=20)),
                ('tourism_type', models.CharField(choices=[('Cultural', 'Cultural (Museums, historical sites)'), ('Adventure', 'Adventure (Hiking, extreme sports)'), ('Relaxation', 'Relaxation (Beaches, spas)'), ('Nature', 'Nature (National parks, wildlife)'), ('Nightlife', 'Nightlife (Bars, clubs)'), ('Family-friendly', 'Family-friendly'), ('Shopping', 'Shopping')], max_length=50)),
                ('cost_level', models.CharField(choices=[('Low', 'Low (Backpacking, hostels)'), ('Medium', 'Medium (Hotels, mid-range restaurants)'), ('High', 'High (Luxury hotels, fine dining)')], max_length=10)),
                ('family_friendly', models.BooleanField(default=False)),
                ('accessibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_destinations', to='destinations.destination')),
            ],
        ),
    ]
